name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  c:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        lang:
          - C
        program:
          - Colleen
          - Grace
          - Sully
        cc:
          - clang
          - gcc
        build:
          - debug
          - release
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Colleen
        if: matrix.program == 'Colleen'
        run: |
          cd ${{ matrix.lang }}
          make Colleen CC=${{ matrix.cc }} BUILD=${{ matrix.build }}
          cd ${{ matrix.build }}
          ./Colleen > Colleen_copy.c
          diff Colleen_copy.c ../Colleen.c
      - name: Grace
        if: matrix.program == 'Grace'
        run: |
          cd ${{ matrix.lang }}
          make Grace CC=${{ matrix.cc }} BUILD=${{ matrix.build }}
          cd ${{ matrix.build }}
          ./Grace
          diff Grace_kid.c ../Grace.c
      - name: Sully
        if: matrix.program == 'Sully'
        run: |
          cd ${{ matrix.lang }}
          make Sully CC=${{ matrix.cc }} BUILD=${{ matrix.build }}
          cd ${{ matrix.build }}
          ./Sully
          ls -al | grep Sully | wc -l > wc.txt
          echo 13 > number.txt
          diff number.txt wc.txt
          diff ../Sully.c ./Sully_0.c | grep '<\|>' > a
          echo -e "<     int i = 5;\n>     int i = 0;" > b
          diff a b
          diff ./Sully_3.c ./Sully_2.c | grep '<\|>' > a
          echo -e "<     int i = 3;\n>     int i = 2;" > b
          diff a b
  asm:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        lang:
          - ASM
        program:
          - Colleen
          - Grace
          - Sully
        as:
          - nasm
        linker:
          - clang
          - gcc
        build:
          - debug
          - release
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: install nasm
        if: matrix.as == 'nasm'
        run: |
          sudo apt update && sudo apt install nasm
      - name: Colleen
        if: matrix.program == 'Colleen'
        run: |
          cd ${{ matrix.lang }}
          make Colleen AS=${{ matrix.as }} LD=${{ matrix.linker }} BUILD=${{ matrix.build }}
          cd ${{ matrix.build }}
          ./Colleen > Colleen_copy.s
          diff Colleen_copy.s ../Colleen.s
      - name: Grace
        if: matrix.program == 'Grace'
        run: |
          cd ${{ matrix.lang }}
          make Grace AS=${{ matrix.as }} LD=${{ matrix.linker }} BUILD=${{ matrix.build }}
          cd ${{ matrix.build }}
          ./Grace
          diff Grace_kid.s ../Grace.s
      - name: Sully
        if: matrix.program == 'Sully'
        run: |
          cd ${{ matrix.lang }}
          make Sully AS=${{ matrix.as }} LD=${{ matrix.linker }} BUILD=${{ matrix.build }}
          cd ${{ matrix.build }}
          ./Sully
          ls -al | grep Sully | wc -l > wc.txt
          echo 13 > number.txt
          diff number.txt wc.txt
          diff ../Sully.s ./Sully_0.s | grep '<\|>' > a
          echo -e "< %define i 5\n> %define i 0" > b
          diff a b
          diff ./Sully_3.s ./Sully_2.s | grep '<\|>' > a
          echo -e "< %define i 3\n> %define i 2" > b
          diff a b
  rust:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        lang:
          - RUST
        program:
          - Colleen
          # - Grace
          # - Sully
        rustc:
          - rustc
        build:
          - debug
          - release
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Colleen
        if: matrix.program == 'Colleen'
        run: |
          cd ${{ matrix.lang }}
          make Colleen RUSTC=${{ matrix.rustc }} BUILD=${{ matrix.build }}
          cd ${{ matrix.build }}
          ./Colleen > Colleen_copy.rs
          diff Colleen_copy.rs ../Colleen.rs
      - name: Grace
        if: matrix.program == 'Grace'
        run: |
          cd ${{ matrix.lang }}
          make Grace RUSTC=${{ matrix.rustc }} BUILD=${{ matrix.build }}
          cd ${{ matrix.build }}
          ./Grace
          diff Grace_kid.rs ../Grace.rs
      - name: Sully
        if: matrix.program == 'Sully'
        run: |
          cd ${{ matrix.lang }}
          make Sully RUSTC=${{ matrix.rustc }} BUILD=${{ matrix.build }}
          cd ${{ matrix.build }}
          ./Sully
          ls -al | grep Sully | wc -l > wc.txt
          echo 13 > number.txt
          diff number.txt wc.txt
          diff ../Sully.rs ./Sully_0.rs | grep '<\|>' > a
          echo -e "<     int i = 5;\n>     int i = 0;" > b
          diff a b
          diff ./Sully_3.rs ./Sully_2.rs | grep '<\|>' > a
          echo -e "<     int i = 3;\n>     int i = 2;" > b
          diff a b
